//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.GetterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetterService.IGetter")]
    public interface IGetter {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetter/GetUnitList", ReplyAction="http://tempuri.org/IGetter/GetUnitListResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] GetUnitList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetter/GetUnitList", ReplyAction="http://tempuri.org/IGetter/GetUnitListResponse")]
        System.Threading.Tasks.Task<object[]> GetUnitListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetter/GetSpeedList", ReplyAction="http://tempuri.org/IGetter/GetSpeedListResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] GetSpeedList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetter/GetSpeedList", ReplyAction="http://tempuri.org/IGetter/GetSpeedListResponse")]
        System.Threading.Tasks.Task<object[]> GetSpeedListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetterChannel : WebApplication.GetterService.IGetter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetterClient : System.ServiceModel.ClientBase<WebApplication.GetterService.IGetter>, WebApplication.GetterService.IGetter {
        
        public GetterClient() {
        }
        
        public GetterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object[] GetUnitList() {
            return base.Channel.GetUnitList();
        }
        
        public System.Threading.Tasks.Task<object[]> GetUnitListAsync() {
            return base.Channel.GetUnitListAsync();
        }
        
        public object[] GetSpeedList() {
            return base.Channel.GetSpeedList();
        }
        
        public System.Threading.Tasks.Task<object[]> GetSpeedListAsync() {
            return base.Channel.GetSpeedListAsync();
        }
    }
}
