//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataClient.myServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://person.com/", ConfigurationName="myServiceReference.getPerson")]
    public interface getPerson {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://person.com/getPerson/GetHoursRequest", ReplyAction="http://person.com/getPerson/GetHoursResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DataClient.myServiceReference.GetHoursResponse GetHours(DataClient.myServiceReference.GetHoursRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://person.com/getPerson/GetHoursRequest", ReplyAction="http://person.com/getPerson/GetHoursResponse")]
        System.Threading.Tasks.Task<DataClient.myServiceReference.GetHoursResponse> GetHoursAsync(DataClient.myServiceReference.GetHoursRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://person.com/getPerson/GetIDRequest", ReplyAction="http://person.com/getPerson/GetIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DataClient.myServiceReference.GetIDResponse GetID(DataClient.myServiceReference.GetIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://person.com/getPerson/GetIDRequest", ReplyAction="http://person.com/getPerson/GetIDResponse")]
        System.Threading.Tasks.Task<DataClient.myServiceReference.GetIDResponse> GetIDAsync(DataClient.myServiceReference.GetIDRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://person.com/getPerson/GetPersonRequest", ReplyAction="http://person.com/getPerson/GetPersonResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DataClient.myServiceReference.GetPersonResponse GetPerson(DataClient.myServiceReference.GetPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://person.com/getPerson/GetPersonRequest", ReplyAction="http://person.com/getPerson/GetPersonResponse")]
        System.Threading.Tasks.Task<DataClient.myServiceReference.GetPersonResponse> GetPersonAsync(DataClient.myServiceReference.GetPersonRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://person.com/getPerson/GetFirstNameRequest", ReplyAction="http://person.com/getPerson/GetFirstNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DataClient.myServiceReference.GetFirstNameResponse GetFirstName(DataClient.myServiceReference.GetFirstNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://person.com/getPerson/GetFirstNameRequest", ReplyAction="http://person.com/getPerson/GetFirstNameResponse")]
        System.Threading.Tasks.Task<DataClient.myServiceReference.GetFirstNameResponse> GetFirstNameAsync(DataClient.myServiceReference.GetFirstNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHours", WrapperNamespace="http://person.com/", IsWrapped=true)]
    public partial class GetHoursRequest {
        
        public GetHoursRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHoursResponse", WrapperNamespace="http://person.com/", IsWrapped=true)]
    public partial class GetHoursResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://person.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int[] @return;
        
        public GetHoursResponse() {
        }
        
        public GetHoursResponse(int[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetID", WrapperNamespace="http://person.com/", IsWrapped=true)]
    public partial class GetIDRequest {
        
        public GetIDRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetIDResponse", WrapperNamespace="http://person.com/", IsWrapped=true)]
    public partial class GetIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://person.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int[] @return;
        
        public GetIDResponse() {
        }
        
        public GetIDResponse(int[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPerson", WrapperNamespace="http://person.com/", IsWrapped=true)]
    public partial class GetPersonRequest {
        
        public GetPersonRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPersonResponse", WrapperNamespace="http://person.com/", IsWrapped=true)]
    public partial class GetPersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://person.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public GetPersonResponse() {
        }
        
        public GetPersonResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFirstName", WrapperNamespace="http://person.com/", IsWrapped=true)]
    public partial class GetFirstNameRequest {
        
        public GetFirstNameRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFirstNameResponse", WrapperNamespace="http://person.com/", IsWrapped=true)]
    public partial class GetFirstNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://person.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public GetFirstNameResponse() {
        }
        
        public GetFirstNameResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface getPersonChannel : DataClient.myServiceReference.getPerson, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getPersonClient : System.ServiceModel.ClientBase<DataClient.myServiceReference.getPerson>, DataClient.myServiceReference.getPerson {
        
        public getPersonClient() {
        }
        
        public getPersonClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public getPersonClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public getPersonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public getPersonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataClient.myServiceReference.GetHoursResponse DataClient.myServiceReference.getPerson.GetHours(DataClient.myServiceReference.GetHoursRequest request) {
            return base.Channel.GetHours(request);
        }
        
        public int[] GetHours() {
            DataClient.myServiceReference.GetHoursRequest inValue = new DataClient.myServiceReference.GetHoursRequest();
            DataClient.myServiceReference.GetHoursResponse retVal = ((DataClient.myServiceReference.getPerson)(this)).GetHours(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataClient.myServiceReference.GetHoursResponse> DataClient.myServiceReference.getPerson.GetHoursAsync(DataClient.myServiceReference.GetHoursRequest request) {
            return base.Channel.GetHoursAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataClient.myServiceReference.GetHoursResponse> GetHoursAsync() {
            DataClient.myServiceReference.GetHoursRequest inValue = new DataClient.myServiceReference.GetHoursRequest();
            return ((DataClient.myServiceReference.getPerson)(this)).GetHoursAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataClient.myServiceReference.GetIDResponse DataClient.myServiceReference.getPerson.GetID(DataClient.myServiceReference.GetIDRequest request) {
            return base.Channel.GetID(request);
        }
        
        public int[] GetID() {
            DataClient.myServiceReference.GetIDRequest inValue = new DataClient.myServiceReference.GetIDRequest();
            DataClient.myServiceReference.GetIDResponse retVal = ((DataClient.myServiceReference.getPerson)(this)).GetID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataClient.myServiceReference.GetIDResponse> DataClient.myServiceReference.getPerson.GetIDAsync(DataClient.myServiceReference.GetIDRequest request) {
            return base.Channel.GetIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataClient.myServiceReference.GetIDResponse> GetIDAsync() {
            DataClient.myServiceReference.GetIDRequest inValue = new DataClient.myServiceReference.GetIDRequest();
            return ((DataClient.myServiceReference.getPerson)(this)).GetIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataClient.myServiceReference.GetPersonResponse DataClient.myServiceReference.getPerson.GetPerson(DataClient.myServiceReference.GetPersonRequest request) {
            return base.Channel.GetPerson(request);
        }
        
        public string GetPerson() {
            DataClient.myServiceReference.GetPersonRequest inValue = new DataClient.myServiceReference.GetPersonRequest();
            DataClient.myServiceReference.GetPersonResponse retVal = ((DataClient.myServiceReference.getPerson)(this)).GetPerson(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataClient.myServiceReference.GetPersonResponse> DataClient.myServiceReference.getPerson.GetPersonAsync(DataClient.myServiceReference.GetPersonRequest request) {
            return base.Channel.GetPersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataClient.myServiceReference.GetPersonResponse> GetPersonAsync() {
            DataClient.myServiceReference.GetPersonRequest inValue = new DataClient.myServiceReference.GetPersonRequest();
            return ((DataClient.myServiceReference.getPerson)(this)).GetPersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataClient.myServiceReference.GetFirstNameResponse DataClient.myServiceReference.getPerson.GetFirstName(DataClient.myServiceReference.GetFirstNameRequest request) {
            return base.Channel.GetFirstName(request);
        }
        
        public string[] GetFirstName() {
            DataClient.myServiceReference.GetFirstNameRequest inValue = new DataClient.myServiceReference.GetFirstNameRequest();
            DataClient.myServiceReference.GetFirstNameResponse retVal = ((DataClient.myServiceReference.getPerson)(this)).GetFirstName(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataClient.myServiceReference.GetFirstNameResponse> DataClient.myServiceReference.getPerson.GetFirstNameAsync(DataClient.myServiceReference.GetFirstNameRequest request) {
            return base.Channel.GetFirstNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataClient.myServiceReference.GetFirstNameResponse> GetFirstNameAsync() {
            DataClient.myServiceReference.GetFirstNameRequest inValue = new DataClient.myServiceReference.GetFirstNameRequest();
            return ((DataClient.myServiceReference.getPerson)(this)).GetFirstNameAsync(inValue);
        }
    }
}
