//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataClient.myServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://web/", ConfigurationName="myServiceReference.getPosition")]
    public interface getPosition {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://web/getPosition/getUnitIDRequest", ReplyAction="http://web/getPosition/getUnitIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DataClient.myServiceReference.getUnitIDResponse getUnitID(DataClient.myServiceReference.getUnitIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web/getPosition/getUnitIDRequest", ReplyAction="http://web/getPosition/getUnitIDResponse")]
        System.Threading.Tasks.Task<DataClient.myServiceReference.getUnitIDResponse> getUnitIDAsync(DataClient.myServiceReference.getUnitIDRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://web/getPosition/getSpeedRequest", ReplyAction="http://web/getPosition/getSpeedResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DataClient.myServiceReference.getSpeedResponse getSpeed(DataClient.myServiceReference.getSpeedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://web/getPosition/getSpeedRequest", ReplyAction="http://web/getPosition/getSpeedResponse")]
        System.Threading.Tasks.Task<DataClient.myServiceReference.getSpeedResponse> getSpeedAsync(DataClient.myServiceReference.getSpeedRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUnitID", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class getUnitIDRequest {
        
        public getUnitIDRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUnitIDResponse", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class getUnitIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long[] @return;
        
        public getUnitIDResponse() {
        }
        
        public getUnitIDResponse(long[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSpeed", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class getSpeedRequest {
        
        public getSpeedRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSpeedResponse", WrapperNamespace="http://web/", IsWrapped=true)]
    public partial class getSpeedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://web/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int[] @return;
        
        public getSpeedResponse() {
        }
        
        public getSpeedResponse(int[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface getPositionChannel : DataClient.myServiceReference.getPosition, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getPositionClient : System.ServiceModel.ClientBase<DataClient.myServiceReference.getPosition>, DataClient.myServiceReference.getPosition {
        
        public getPositionClient() {
        }
        
        public getPositionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public getPositionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public getPositionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public getPositionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataClient.myServiceReference.getUnitIDResponse DataClient.myServiceReference.getPosition.getUnitID(DataClient.myServiceReference.getUnitIDRequest request) {
            return base.Channel.getUnitID(request);
        }
        
        public long[] getUnitID() {
            DataClient.myServiceReference.getUnitIDRequest inValue = new DataClient.myServiceReference.getUnitIDRequest();
            DataClient.myServiceReference.getUnitIDResponse retVal = ((DataClient.myServiceReference.getPosition)(this)).getUnitID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataClient.myServiceReference.getUnitIDResponse> DataClient.myServiceReference.getPosition.getUnitIDAsync(DataClient.myServiceReference.getUnitIDRequest request) {
            return base.Channel.getUnitIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataClient.myServiceReference.getUnitIDResponse> getUnitIDAsync() {
            DataClient.myServiceReference.getUnitIDRequest inValue = new DataClient.myServiceReference.getUnitIDRequest();
            return ((DataClient.myServiceReference.getPosition)(this)).getUnitIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataClient.myServiceReference.getSpeedResponse DataClient.myServiceReference.getPosition.getSpeed(DataClient.myServiceReference.getSpeedRequest request) {
            return base.Channel.getSpeed(request);
        }
        
        public int[] getSpeed() {
            DataClient.myServiceReference.getSpeedRequest inValue = new DataClient.myServiceReference.getSpeedRequest();
            DataClient.myServiceReference.getSpeedResponse retVal = ((DataClient.myServiceReference.getPosition)(this)).getSpeed(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataClient.myServiceReference.getSpeedResponse> DataClient.myServiceReference.getPosition.getSpeedAsync(DataClient.myServiceReference.getSpeedRequest request) {
            return base.Channel.getSpeedAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataClient.myServiceReference.getSpeedResponse> getSpeedAsync() {
            DataClient.myServiceReference.getSpeedRequest inValue = new DataClient.myServiceReference.getSpeedRequest();
            return ((DataClient.myServiceReference.getPosition)(this)).getSpeedAsync(inValue);
        }
    }
}
